name: DBBS

on:
  push:
    branches:
      - main
  schedule:
    - cron: '59 */5 * * *'  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Notify Discord - Start
      run: |
        curl -H "Content-Type: application/json" \
             -X POST \
             -d "{\"content\": \"Workflow started for $GITHUB_REPOSITORY on $GITHUB_REF by $GITHUB_ACTOR\"}" \
             ${{ secrets.DISCORD_WEBHOOK_URL }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install discord aiohttp beautifulsoup4

    - name: Run bot
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
      run: |
        python bot.py & python playlist_up.py

    - name: Notify Discord - Success
      if: success()
      run: |
        curl -H "Content-Type: application/json" \
             -X POST \
             -d "{\"content\": \"Workflow succeeded for $GITHUB_REPOSITORY on $GITHUB_REF\"}" \
             ${{ secrets.DISCORD_WEBHOOK_URL }}

    - name: Notify Discord - Failure
      if: failure()
      run: |
        curl -H "Content-Type: application/json" \
             -X POST \
             -d "{\"content\": \"Workflow failed for $GITHUB_REPOSITORY on $GITHUB_REF\"}" \
             ${{ secrets.DISCORD_WEBHOOK_URL }}

    - name: Notify Discord - Completed
      if: always()
      run: |
        curl -H "Content-Type: application/json" \
             -X POST \
             -d "{\"content\": \"Workflow completed for $GITHUB_REPOSITORY on $GITHUB_REF\"}" \
             ${{ secrets.DISCORD_WEBHOOK_URL }}
